export enum ColorsName {
   BG_PAGE='BG_BLACK',
   BG_CARD='BG_CARD',
   BG_CONTAINER='BG_CONTAINER',
   BG_INPUT='BG_INPUT',
   TEXT_DEFAULT='TEXT_DEFAULT',
   TEXT_SECONDARY='TEXT_SECONDARY',
   TEXT_PLACEHOLDER='TEXT_PLACEHOLDER',
   GRASS='GRASS',
   BORDER_DEFAULT='BORDER_DEFAULT'
}

export const Colors = {
   [ColorsName.BG_PAGE]: '#0F0F0F',
   [ColorsName.BG_CARD]: '#1E1E1E',
   [ColorsName.BG_CONTAINER]: '#323232',
   [ColorsName.BG_INPUT]: '#1E1E1E',
   [ColorsName.TEXT_DEFAULT]: '#FEFEFE',
   [ColorsName.TEXT_SECONDARY]: '#BFC0C0',
   [ColorsName.TEXT_PLACEHOLDER]: '#919CAA',
   [ColorsName.GRASS]: '#59BE5F',
   [ColorsName.BORDER_DEFAULT]: '#353538'
}